apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090  # Host network modunda localhost
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://localhost:9411  # Host network modunda localhost
    editable: true
